#!/bin/bash

function usage {
    echo "USAGE dtstart pattern"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

PAT="$1"

while read container
do
    docker start $container
done < <(docker ps -a --format "{{.Names}}" | grep "$PAT")

