#!/bin/bash
# needs putty-tools

function usage {
	echo "USAG: $(basename $0) [-h host] [-u user] [-p port] [-k key] [-f] [-y]"
	echo "    -h host: the destination host to copy the id to"
	echo "    -u user: the user at the destination host (default: whoami)"
	echo "    -p port: the ssh port at the destination host (default: 22)"
	echo "    -k key:  the ssh key to authenticate at the destination host (default: password authentication)"
	echo "    -f:      force the generation of the ssh key even it already exists"
	echo "    -y:      Also create a putty key *.ppk"
	exit 1
}

USER="$(whoami)"
HOST=''
PORT=22
OWNKEY=''
FORCE=0
PUTTY=0

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
   	-h)
   	 	HOST="$2"
   	 	shift 2
   	 	;;
   	-u)
   	 	USER="$2"
   	 	shift 2
   	 	;;
   	-p)
   	 	PORT="$2"
   	 	shift 2
   	 	;;
   	-k)
   	 	OWNKEY="$2"
   	 	shift 2
   	 	;;
   	-f)
   	 	FORCE=1	
   	 	shift
   	 	;;
   	-y)
   	 	PUTTY=1	
   	 	shift
   	 	;;
   	 *)
   		usage
   	 	;;
	esac
done

if [ "${HOST}" == "last" -a -f $(dirname $0)/.host ]; then
    HOST=$(cat $(dirname $0)/.host)
else
    echo "${HOST}" > $(dirname $0)/.host
fi

KEY=~/.ssh/${USER}

if [ "${OWNKEY}" != "" ]; then
	OWNKEY=~/.ssh/${OWNKEY}
	if [ ! -f ${OWNKEY} ]; then
		echo "The given key does not exist!"
		exit 1
	fi
fi

if [ ! -f ${KEY} -o ${FORCE} -eq 1 ]; then
	echo "Generating your ssh key..."
	ssh-keygen -q -C "${USER}s key" -N '' -b 4096 -f ${KEY}
	if [ ${PUTTY} -eq 1 ]; then
		echo "Generating your putty key..."
		puttygen ${KEY} -o ${KEY}.ppk
	fi
else
	echo "Your ssh key exists."
fi

if [ "${OWNKEY}" != "" ]; then
	if [ -f ${OWNKEY} ]; then
		echo "Copy ID to ${USER}@${HOST}:${PORT} using key ${OWNKEY}"
		scp -i ${OWNKEY} -P ${PORT} ${KEY}.pub ${USER}@${HOST}:.ssh
		ssh -i ${OWNKEY} ${USER}@${HOST} -p ${PORT} 'cat .ssh/${USER}.pub >> .ssh/authorized_keys'
	else 
		echo "Key ${OWNKEY} does not exist!"
	fi
elif [ "${HOST}" != "" -a -f ${KEY} ]; then
	echo "Copy ID to ${USER}@${HOST}:${PORT}"
	ssh-copy-id -i $KEY ${USER}@${HOST} -p ${PORT}
fi
